name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'def-not-a-game-studio',
              repo: 'docs',
              workflow_id: 'main.yml',
              ref: 'main'
            });
          
