name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          cd ~
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Clone our GH-Pages repository
        run: |
          git clone https://github.com/def-not-a-game-studio/docs ~/gh-pages

      - name: Build documentation
        run: |
          ./mkdocs/mkdocs build --clean --strict --site-dir ~/rathena/doc

      - name: Deploy
        run: |
          cd ~/gh-pages
          git add . & git commit -m "${{ github.event.head_commit.message }}" & git push origin main
          
